version: "3"

services:
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  keycloak:
    image: "quay.io/keycloak/keycloak:latest"
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_DB_USERNAME=mongo
      - KEYCLOAK_DB_PASSWORD=mongo
      - KEYCLOAK_DB_HOST=mongodb
      - KEYCLOAK_DB_PORT=27017
